"""baseline plus cascade ondelete, indexes, drop google_token_json

Revision ID: 74bf5b968796
Revises: 
Create Date: 2026-08-15 15:23:44.748358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74bf5b968796'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_public_calendarevent_relatedpersonid'), 'calendarevent', ['relatedpersonid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_calendarevent_userid'), 'calendarevent', ['userid'], unique=False, schema='public')
    op.drop_constraint('calendarevent_relatedpersonid_fkey', 'calendarevent', type_='foreignkey')
    op.drop_constraint('calendarevent_userid_fkey', 'calendarevent', type_='foreignkey')
    op.create_foreign_key(None, 'calendarevent', 'knownperson', ['relatedpersonid'], ['personid'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'calendarevent', 'users', ['userid'], ['userid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_index(op.f('ix_public_conversation_personid'), 'conversation', ['personid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_conversation_userid'), 'conversation', ['userid'], unique=False, schema='public')
    op.drop_constraint('conversation_personid_fkey', 'conversation', type_='foreignkey')
    op.drop_constraint('conversation_userid_fkey', 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'knownperson', ['personid'], ['personid'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(None, 'conversation', 'users', ['userid'], ['userid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_index(op.f('ix_public_emotionrecord_interactionid'), 'emotionrecord', ['interactionid'], unique=False, schema='public')
    op.drop_constraint('emotionrecord_interactionid_fkey', 'emotionrecord', type_='foreignkey')
    op.create_foreign_key(None, 'emotionrecord', 'conversation', ['interactionid'], ['interactionid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_index(op.f('ix_public_faceencoding_personid'), 'faceencoding', ['personid'], unique=False, schema='public')
    op.drop_constraint('faceencoding_personid_fkey', 'faceencoding', type_='foreignkey')
    op.create_foreign_key(None, 'faceencoding', 'knownperson', ['personid'], ['personid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_index(op.f('ix_public_note_interactionid'), 'note', ['interactionid'], unique=False, schema='public')
    op.drop_constraint('note_interactionid_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'conversation', ['interactionid'], ['interactionid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('usercaregiver_caregiverid_fkey', 'usercaregiver', type_='foreignkey')
    op.drop_constraint('usercaregiver_userid_fkey', 'usercaregiver', type_='foreignkey')
    op.create_foreign_key(None, 'usercaregiver', 'users', ['userid'], ['userid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'usercaregiver', 'caregiver', ['caregiverid'], ['caregiverid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('userknownperson_userid_fkey', 'userknownperson', type_='foreignkey')
    op.drop_constraint('userknownperson_personid_fkey', 'userknownperson', type_='foreignkey')
    op.create_foreign_key(None, 'userknownperson', 'users', ['userid'], ['userid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'userknownperson', 'knownperson', ['personid'], ['personid'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('users', 'google_token_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_token_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'userknownperson', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'userknownperson', schema='public', type_='foreignkey')
    op.create_foreign_key('userknownperson_personid_fkey', 'userknownperson', 'knownperson', ['personid'], ['personid'])
    op.create_foreign_key('userknownperson_userid_fkey', 'userknownperson', 'users', ['userid'], ['userid'])
    op.drop_constraint(None, 'usercaregiver', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'usercaregiver', schema='public', type_='foreignkey')
    op.create_foreign_key('usercaregiver_userid_fkey', 'usercaregiver', 'users', ['userid'], ['userid'])
    op.create_foreign_key('usercaregiver_caregiverid_fkey', 'usercaregiver', 'caregiver', ['caregiverid'], ['caregiverid'])
    op.drop_constraint(None, 'note', schema='public', type_='foreignkey')
    op.create_foreign_key('note_interactionid_fkey', 'note', 'conversation', ['interactionid'], ['interactionid'])
    op.drop_index(op.f('ix_public_note_interactionid'), table_name='note', schema='public')
    op.drop_constraint(None, 'faceencoding', schema='public', type_='foreignkey')
    op.create_foreign_key('faceencoding_personid_fkey', 'faceencoding', 'knownperson', ['personid'], ['personid'])
    op.drop_index(op.f('ix_public_faceencoding_personid'), table_name='faceencoding', schema='public')
    op.drop_constraint(None, 'emotionrecord', schema='public', type_='foreignkey')
    op.create_foreign_key('emotionrecord_interactionid_fkey', 'emotionrecord', 'conversation', ['interactionid'], ['interactionid'])
    op.drop_index(op.f('ix_public_emotionrecord_interactionid'), table_name='emotionrecord', schema='public')
    op.drop_constraint(None, 'conversation', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'conversation', schema='public', type_='foreignkey')
    op.create_foreign_key('conversation_userid_fkey', 'conversation', 'users', ['userid'], ['userid'])
    op.create_foreign_key('conversation_personid_fkey', 'conversation', 'knownperson', ['personid'], ['personid'])
    op.drop_index(op.f('ix_public_conversation_userid'), table_name='conversation', schema='public')
    op.drop_index(op.f('ix_public_conversation_personid'), table_name='conversation', schema='public')
    op.drop_constraint(None, 'calendarevent', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'calendarevent', schema='public', type_='foreignkey')
    op.create_foreign_key('calendarevent_userid_fkey', 'calendarevent', 'users', ['userid'], ['userid'])
    op.create_foreign_key('calendarevent_relatedpersonid_fkey', 'calendarevent', 'knownperson', ['relatedpersonid'], ['personid'])
    op.drop_index(op.f('ix_public_calendarevent_userid'), table_name='calendarevent', schema='public')
    op.drop_index(op.f('ix_public_calendarevent_relatedpersonid'), table_name='calendarevent', schema='public')
    # ### end Alembic commands ###
